export const experienceData = [
  {
    id: 1,
    title: "MERN Stack Development Training",
    type: "Learning Experience",
    period: "2025 - 2026",
    description:
      "Focused on building fullstack web applications using React, Node.js, Express.js, MongoDB, authentication, APIs, and deployment workflows.",
    highlights: [
      "Learned React component-based architecture",
      "Built REST APIs using Node.js and Express.js",
      "Worked with MongoDB, Mongoose, and aggregation pipeline",
      "Implemented JWT authentication and role-based access",
      "Practiced Git, GitHub, Postman, and project workflow",
    ],
    technologies: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Mongoose",
      "JWT",
      "Git",
      "GitHub",
      "Postman",
    ],
  },

  {
    id: 2,
    title: "SolveX - Student Doubt Solving Platform",
    type: "Major Project",
    period: "2026",
    description:
      "Worked on a real-time student doubt solving platform where students can connect with verified mentors based on skills, price, time, and availability.",
    highlights: [
      "Designed student and mentor interaction flow",
      "Implemented role-based dashboard structure",
      "Worked on authentication with access and refresh token flow",
      "Planned real-time mentor matching using Socket.IO",
      "Used MongoDB aggregation for admin and student dashboard data",
      "Deployed project with Docker and AWS EKS setup",
    ],
    technologies: [
      "React.js",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Socket.IO",
      "Redux Toolkit",
      "Docker",
      "AWS EKS",
    ],
  },

  {
    id: 3,
    title: "Authentication System",
    type: "Backend Module",
    period: "2026",
    description:
      "Built a secure authentication module with registration, OTP verification, login, refresh token regeneration, logout, and protected routes.",
    highlights: [
      "Implemented OTP-based user verification",
      "Used bcrypt for password hashing",
      "Created JWT access token and refresh token flow",
      "Handled HTTP-only refresh token cookies",
      "Created protected API middleware",
      "Managed common authentication errors and API responses",
    ],
    technologies: [
      "Node.js",
      "Express.js",
      "MongoDB",
      "Mongoose",
      "JWT",
      "Bcrypt",
      "Redis",
      "Nodemailer",
    ],
  },

  {
    id: 4,
    title: "Mentor Assessment & Verification System",
    type: "Project Feature",
    period: "2026",
    description:
      "Worked on mentor verification flow where mentors attend category-based MCQ assessment before becoming verified on the platform.",
    highlights: [
      "Planned mentor assessment flow",
      "Added attempt limit and verification rules",
      "Designed warning logic for tab switch and focus loss",
      "Planned AI-based result analysis",
      "Created pass/fail email notification flow",
      "Connected mentor verification status with platform access",
    ],
    technologies: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Redis",
      "JWT",
      "Email Service",
      "Generative AI",
    ],
  },

  {
    id: 5,
    title: "GitHub Project Tracker",
    type: "Developer Tool Project",
    period: "2026",
    description:
      "Worked on a GitHub repository tracking system that listens to webhook events, stores repository metadata, and tracks project updates.",
    highlights: [
      "Integrated GitHub App workflow",
      "Handled GitHub webhook events",
      "Stored repository metadata in database",
      "Used event-driven backend architecture",
      "Worked with Redis queue planning",
      "Explored Kubernetes-based sandbox architecture",
    ],
    technologies: [
      "Node.js",
      "Express.js",
      "MongoDB",
      "Redis",
      "Octokit",
      "GitHub Webhook",
      "Docker",
      "Kubernetes",
    ],
  },

  {
    id: 6,
    title: "Cloud & Deployment Practice",
    type: "DevOps Practice",
    period: "2026",
    description:
      "Practiced containerization, cloud deployment, static Express deployment, routing, and AWS-based infrastructure setup.",
    highlights: [
      "Used Docker for project deployment",
      "Worked with AWS EKS deployment",
      "Used AWS S3 Bucket and Route 53 basics",
      "Practiced GitHub Actions and CI/CD pipeline",
      "Handled frontend-backend proxy setup with Axios",
      "Worked on static Express deployment approach",
    ],
    technologies: [
      "Docker",
      "Kubernetes",
      "AWS",
      "AWS EKS",
      "AWS S3",
      "AWS Route 53",
      "GitHub Actions",
      "CI/CD",
    ],
  },
];